Fix ruta changelog definitiva

diff --git a/liquibase/CHANGES/DML/00_INSERTS/.github/workflows/liquibase.yml b/liquibase/CHANGES/DML/00_INSERTS/.github/workflows/liquibase.yml
--- a/liquibase/CHANGES/DML/00_INSERTS/.github/workflows/liquibase.yml
+++ b/liquibase/CHANGES/DML/00_INSERTS/.github/workflows/liquibase.yml
@@ -19,9 +19,9 @@ jobs:
           ls -R
 
           echo "Buscando changelog..."
-          if test -f liquibase/changelog.yml; then
-            echo "Changelog encontrado ✅"
-          else
-            echo "ERROR: Falta changelog ❌"
-            exit 1
-          fi 
+         if [ -f ./liquibase/changelog.yml ]; then
+  echo "Changelog encontrado ✅"
+else
+  echo "ERROR: Falta changelog ❌"
+  exit 1
+fi 
